### ISSUE TITLE
Unclear Purpose

### ISSUE THREAD

**Issue by geirman** [TBouder/react-native-asset-resize-to-base64#1]
Thanks for creating this project, but I'm not certain what it's primary use case is. If I understand it correctly, I can pull an image from the gallery, convert it to base64, then resize the base64 encoded image, which would return a new base64 string. Is that right?

**Comment by TBouder** [comment]
Hi @geirman !
Yes, I have to make the Readme a little bit more clear and add a full example (Todo of the day)

That's right : 
- You can get the image from the gallery with CameraRoll (returns an url like this : "assets-library://asset/asset.JPG?id=ED7AC36B-A150-4C38-BB8C-B6D696F4F2ED&ext=JPG")
- Then, you can use "NativeModules.RNAssetResizeToBase64.assetToResizedBase64" with 3 args (The asset's url, the width and the height) and the callback (err/success)
- This function, on success, gives you the base64 string for this resized image 

Is that clear ?
Thanks

**Comment by geirman** [comment]
Indeed, that clears it up. I think this may be useful to me, so thank you!

**Comment by TBouder** [comment]
Hi again !
There is a new Readme and an example here : https://github.com/TBouder/react-native-asset-resize-to-base64/tree/master/AssetResizeExample :)

Do not hesitate if you have an issue !
Thanks
