### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by xyy7260** [TBouder/react-native-asset-resize-to-base64#2]
- 能否给一个实现的demo，和其他组件一样的吗，

- 如果更新，这组件很不错
@TBouder

**Comment by TBouder** [comment]
Hi,

I am sorry but I do not speak Chinese, but thanks to google trad, I think I understand that you want an example for this package, isn't it ?
If I am right, you can find an example here : https://github.com/TBouder/react-native-asset-resize-to-base64/blob/master/AssetResizeExample/index.android.js

Thank You,
Thomas

**Comment by xyy7260** [comment]
Sorry, I forgot and translated yesterday.
This component supports IOS and android,
Thank you for

**Comment by xyy7260** [comment]
Thank you for your enthusiasm
Components are available in IOS and android

**Comment by xyy7260** [comment]
Components can be used in IOS and android.
Can it compress some images?

Thank you for your enthusiasm

**Comment by TBouder** [comment]
Hi ! 
You can use it for IOS and Android, and you can specify image size.

```
NativeModules.RNAssetResizeToBase64.assetToResizedBase64(
    url, //The local image url
    500, //New width
    500, //New height
    callback() //Callback
)
```
